### ISSUE TITLE
Set schedule improvements: Accept abbreviations (e.g. mon, tue) and match case-insensitive

### ISSUE THREAD

**Issue by ChrisRenfrow** [dimriver/pairing-bot#30]
It would be nice if pairing bot recognized abbreviations for days. Also it seems like it might make sense if the input was sanitized of unexpected characters, and converted to lower-case for case-insensitive matching. I'm willing to put in the work for this and will take a look sometime this week, just adding an issue to start the conversation. :)

**Comment by dimriver** [comment]
Hey Chris! This sounds great and I'll gladly merge any changes you make toward this issue. Please also reach out to @RobertXu who's also doing some Pairing Bot work right now. You may need to coordinate your work because he's making some larger changes. He's got an open PR you can look at [here](https://github.com/dimriver/pairing-bot/pulls), or you can just poke around in the `dev` branch

**Comment by RobertXu** [comment]
Yeah, I'm totally down to pair on this!

For reference here's where the days of the week strings are currently stored: https://github.com/dimriver/pairing-bot/blob/main/parse_cmd.go#L27

**Comment by RobertXu** [comment]
@ChrisRenfrow 

This has now been fixed! I added the common abbreviations for the days of the week, but feel free to add any extras here: https://github.com/dimriver/pairing-bot/blob/main/parse_cmd.go#L34
